version: '3.9'

services:
  wallet-db:
    image: mariadb
    container_name: wallet-db
    hostname: wallet-db
    restart: always
    network_mode: host
    expose: 
      - 3307
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: myuser
      MARIADB_PASSWORD:
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./db-setup/scripts/:/docker-entrypoint-initdb.d/

  wallet-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wallet-phpmyadmin
    hostname: wallet-phpmyadmin
    network_mode: host
    environment:
      APACHE_PORT: 8081
      PMA_HOST: 127.0.0.1
      PMA_PORT: 3307

  wallet-cache:
    image: redis:6.2-alpine
    container_name: wallet-cache
    hostname: wallet-cache
    network_mode: host
    restart: always  
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  wallet-enterprise-diploma-issuer:
    container_name: wallet-enterprise-diploma-issuer
    build:
      context: $PWD/wallet-enterprise-diploma-issuer
      dockerfile: development.Dockerfile
    image: wallet-enterprise-diploma-issuer
    restart: always
    network_mode: host
    volumes:
      - ./wallet-enterprise-diploma-issuer:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G

  wallet-enterprise-vid-issuer:
    container_name: wallet-enterprise-vid-issuer
    build:
      context: $PWD/wallet-enterprise-vid-issuer
      dockerfile: development.Dockerfile
    image: wallet-enterprise-vid-issuer
    restart: always
    network_mode: host
    volumes:
      - ./wallet-enterprise-vid-issuer:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G

  wallet-backend-server:
    container_name: wallet-backend-server
    build:
      context: $PWD/wallet-backend-server
      dockerfile: development.Dockerfile
    image: wallet
    restart: always
    network_mode: host
    volumes:
      - ./wallet-backend-server:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G

  wallet-mock:
    container_name: wallet-mock
    build:
      context: $PWD/wallet-backend-server/samples/wallet-mock
      dockerfile: development.Dockerfile
    image: wallet-mock
    restart: always
    network_mode: host
    volumes:
      - ./wallet-backend-server/samples/wallet-mock:/home/node/app
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G

  enterprise-verifier-core:
    container_name: enterprise-verifier-core
    build:
      context: $PWD/enterprise-verifier-core
      dockerfile: development.Dockerfile
    image: enterprise-verifier-core
    restart: always
    network_mode: host
    volumes:
      - ./enterprise-verifier-core:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G
volumes:
  datadir:
  cache:
    driver: local
